### ISSUE TITLE
ImportError: libconsole_bridge.so.0.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nokonjina** [ros-melodic-arch/ros-melodic-qt-gui-cpp#16]
After running rqt i get this error
`Could not import "pyqt" bindings of qt_gui_cpp library - so C++ plugins will not be available:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python3.8/site-packages/qt_gui_cpp/cpp_binding_helper.py", line 43, in <module>
    from . import libqt_gui_cpp_sip
ImportError: libconsole_bridge.so.0.4: cannot open shared object file: No such file or directory` ,
and when running rviz or roslaunch(where i use gazebo) i get this:
`error while loading shared libraries: libconsole_bridge.so.0.4: cannot open shared object file: No such file or directory`
I got libconsole_bridge.so.1.0 version

**Comment by bionade24** [comment]
Have you installed ros via my repos or via AUR?

**Comment by nokonjina** [comment]
I use oscloud repository

**Comment by bionade24** [comment]
> I use oscloud repository

Try:
`aur_helper -S $(pacman -Qs ros-melodic | awk ' NR % 2 == 1 { print substr($1, 7) } ')`
We don't increase pkgrels on ABI changes.

**Comment by nokonjina** [comment]
Thank you
