### ISSUE TITLE
Compiler can't find Qt5 libraries

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-qt-gui-cpp#4]
The same issue is occurring in this package as did in `ros-melodic-rviz` (https://github.com/ros-melodic-arch/ros-melodic-rviz/issues/4).

```
g++: error: 0/libQt5Core.so: No such file or directory
make[3]: *** [Makefile:38: "/home/acxz/.cache/yay/ros-melodic-qt-gui-cpp/src/build/devel/lib/python3.7/site-packages/qt_gui_cpp/libqt_gui_cpp_sip".so] Error 1
make[2]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/build.make:61: devel/lib/python3.7/site-packages/qt_gui_cpp/libqt_gui_cpp_sip.so] Error 2
make[1]: *** [CMakeFiles/Makefile2:380: src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: ros-melodic-qt-gui-cpp
```

Changing the `QT_INSTALL_LIB` env var to `/usr/lib` also gives the same error:
```
/bin/sh: /usr/lib: syntax error: operand expected (error token is "/usr/lib")
```

Seems like something happened upstream with `sip` bindings which is causing subsequent builds based of that building/ upstream packages that use `sip` haven't yet fixed the issue on their end.

Keeping this issue here, until it is posted somewhere upstream (wether it be `sip`, `qt-gui-cpp`, or even `QT`; I honestly don't know) and until this specific package is patched with a similar fix to https://github.com/ros-melodic-arch/ros-melodic-rviz/pull/5.

**Comment by bionade24** [comment]
Solved with https://github.com/ros-melodic-arch/ros-melodic-qt-gui-cpp/pull/5

**Comment by acxz** [comment]
I think this issue should still be open until an upstream issue somewhere else is made.

**Comment by acxz** [comment]
I believe it is fine to close this issue since https://github.com/ros-visualization/python_qt_binding/pull/64 has been merged.

**Comment by bionade24** [comment]
No, we keep this open with patched label until we remove the patch because we have a new upstream release. It can take months from getting merged to a new release.

**Comment by acxz** [comment]
Understood, I will try to reopen the issues we have closed before concerning patches.

**Comment by acxz** [comment]
Closing issue since #10 and https://github.com/ros-melodic-arch/ros-melodic-python-qt-binding/pull/2 got merged.
