### ISSUE TITLE
install error : 

### ISSUE THREAD

**Issue by hammer124** [ros-melodic-arch/ros-melodic-qt-gui-cpp#8]
The error message: 48%] Running Shiboken generator for libqt_gui_cpp Python bindings... /bin/sh: --generatorSet=shiboken: command not found make[2]: [src/qt_gui_cpp_shiboken/CMakeFiles/qt_gui_cpp_shiboken.dir/build.make:75: src/qt_gui_cpp_shiboken/libqt_gui_cpp_shiboken/libqt_gui_cpp_shiboken_module_wrapper.cpp] Error 127 make[1]: [CMakeFiles/Makefile2:330: src/qt_gui_cpp_shiboken/CMakeFiles/qt_gui_cpp_shiboken.dir/all] Error 2 make: *** [Makefile:130: all] Error 2 sed: can't read src/build/sip/qt_gui_cpp_sip/Makefile: No such file or directory ==> ERROR: A failure occurred in build(). Aborting...

**Comment by jwhendy** [comment]
Happen to peruse old issues? Like [this one](https://github.com/ros-melodic-arch/ros-melodic-qt-gui-cpp/issues/6)? I would:

1) please use code formatting
2) suggest the things you've done to troubleshoot already
3) try the relevant things from #6 
4) post the full build output vs. just the last error string; sometimes the initial config process has more human readable errors than what cmake spits out when it actually breaks

**Comment by acxz** [comment]
This package has been updated on the AUR, @hammer124 let us know you still cannot uninstall it.

**Comment by hammer124** [comment]
> This package has been updated on the AUR, @hammer124 let us know you still cannot uninstall it.

still can't install
is there any log file that can help us?

**Comment by acxz** [comment]
Is it the same error? If it has anything to do with boost, you will need to rebuild all of ROS.
If you are still getting a similar error with shiboken maybe this PR https://github.com/ros-melodic-arch/ros-melodic-python-qt-binding/pull/3 will fix it? Can you try that branch and test to see if it resolves your issue?

**Comment by jwhendy** [comment]
Also, per above, please do this:

>4. post the full build output vs. just the last error string; sometimes the initial config process has more human readable errors than what cmake spits out when it actually breaks

Just look for where the build stops looking "normal" and starts looking like errors and paste it in here (in a code block) and we'll take a look.

**Comment by acxz** [comment]
@hammer124 if you are not using `shiboken2` for anything and do not want to wait for the repo to sync to the AUR then the quick and easy fix might be to just
`yay -Rns shiboken2`

**Comment by hammer124** [comment]
> @hammer124 if you are not using `shiboken2` for anything and do not want to wait for the repo to sync to the AUR then the quick and easy fix might be to just
> `yay -Rns shiboken2`

by unistalling shiboken2 , pyside2 , python-pyside 
finally build completed 
thank all of you
